-- Database creation
CREATE DATABASE wealthWise;

-- Users Table creation
CREATE TABLE Users (
    UserID SERIAL PRIMARY KEY,
    Email VARCHAR(55) UNIQUE NOT NULL,
    Password VARCHAR(55) NOT NULL,
    FullName VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- Initialize Database
USE wealthWise;